sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '6'
branches:
  only:
  - develop
  - master
  - testing/permissions
  - feature/debugging-tests
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: xQQEo+EtbJkzgG8peEhrIkXvq96RWsWQ3HSZTNrS/k11DEjp1//8m1yHk7JrM1sCz8rdEbvyQz79LQvAqN2UwQCIiExRs9NGh+tgHPfNrCk0pXRHNqaCrSSbcZGIXLaxDddUKXbOFqfOxjs7PhyFNjzcVN81GQ7E7fRLqfF75YYG1IY2kzMz7uuPYVB/uZ+EfWgJtoXNZy3vbLu8g5be6PHLj3nQGDU46IGUFLXxuANRzUC73EfKWNWaRRDw34Q7ThH767fvQkmX7CcO4v1EeHfvPMMXBAhyCF7kTQPkXXB+dmuirJKGNfD/7LX5/hSKBwvNKE5ZBLkCPVvLy7M627JuP61v87P9udLPcmrGeUBnfPq6s1oIHE+ihkeJGyGjKaFnOkVYx2B/3L+rHSk14cepsnhnP3dXgs2DPVsKZbilkstFQWbaGnpk3DMFpBGvh4GI/TPYXupNVn01Y5huNG5KITe7nEwO5nhow8L5gxZmLsHLI0W4bM+0SZmIdD3rfmz/jdfgUbfk9noXKP21q1Gf9+qlFqgE36yYqzzYq4xjyQus93wHxEaV7UqUz7Ici/PQE1o2yIQifa1tMQJvx7rhr+paToX95LrRF+4xRXL9+5iTwQDbRvKgUUB8cDi5d7RMyhn9upBfnEWAgDHCqgLb9M2rqU1yq2oi6HS16cM=
before_install:
- export CEDAR_HOST=staging.metadatacenter.net
- export CEDAR_PROFILE=server
- export CEDAR_ANALYTICS_KEY=false
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
- npm install -g gulp
- npm install -g protractor
- webdriver-manager update
- nohup bash -c "webdriver-manager start 2>&1 &"
script:
- gulp test-permissions
env:
  global:
  - secure: upSQEvtBEuKEu8lZlgwfIImNIvnK3I5djNu439Z122smtS9jjmqvUiYbn+nF8og+B5wL+SHcE7lgaPEza7m5seWB6nRjNMKieAP+AoS66h1zOBychVwzgGTyBv7UYwv0WyMmpSflrt8tUf0ohXgaDgkXgS0TzKUlPuYEbjRNemduHN51xCDFUCfa/sd0KV8xgJ2eYOGE0CnDDeG+xQZSUODbWGpKvzUAsH0Yl4F1aXpo7q7aROqmhw28N4Tmk8boWpsmyyK6q8UXpQb0wa147UGbLZ5yE7TqFUt6O66LMIBPIYwRxX5GxTvCpwRR80uTWuzgAZjH1RZuiiQih1+HdlJBzOM/RD0C9z5zkoXo6r0oqcuPaRNzApAlCWjBGliEZ4nNreixOVlzbJ70vPnje18JvprETcw5aPoF3Mnmw3vt6kiCL5sQnQ8R2O8jx6uRL3ZSeIm4U5ixxaF4uCAToMduXNoSFI36ivGAkin9uNm5zh0O+y9SWVwv0HH7goUKknlQxhx7KktDaEy+Fn5s1i+Yo67TYhD1l47I36DlxYtivj9IB4mx4KmHzN23wHQC1AZbB0zUo2qKvKVA4X1aZ+AqNtWQAoqTZVV3Rp5QOTrTNf5gxAvnhyESBpEVf+ZADCAjbmH+3nsgDUEUvtef+FupEQ5baVGMaq/GPFzbIFM=
  - secure: dnsUEpWqOV72vfR0SXsKZflXEqDMUcylQiFkkWiKWP/EFGSCcPdMcURI18bicNUo+1zFlBM0RblH3dGDjYmIjkoL8Q5VJtK0t7OQKrJpTR7KQvEQV17SqwZfKURlNbdFafMfhQJcZN9dX2IErxxpDmTZlJxtSb55vKo3/H9pgcFI20CWwMVWcKR2KeSIbIB0/UG3SCeZZvGG+mQgwUNcdtB8q8bGKfgk0SCDQP2FCXb4ywEWYqfI2fEE/XVTT0RkNcjNs0fMdJ4HAlvrED79Tjyjz5zBDx6JeTUpKEtkpL59KmMn/dAQavWxjgPZ8XF/4FME/kd0RN9Qq92sN5XQSpJUMcQm5YD0IoMWkDxbJkUDgTXe0D+FnZTYPJnri6qhdwPm3VVJCfJ3kQVh2TrUzpGrJeu6XFmCaRd+zku+0qWMPf4a5JU3mDXZRcTnlEo0koLZCnmKOYEEIByVmP8/5Up4zQOPp7ZyCIUW1rksWtZsFEOLRpGM6ixf+pis7/rGl+LHQo+MCGIAnxInyx4MJOORv+XmWp0UmZAjdREZ0tDIHYzd+0SMzP+4tlxkvDNZrBJI9qir7SjwkCDLdGghAXSvhlOLemj6nrqhhP0eO+JWdHNhm9BN6AmY0lBf3o1Ho+xSxHqsrUQoYPkvqAalAL0NrFJsVFfHrlqH8aUMuIE=
  - CEDAR_TEST_USER1_EMAIL="test1@test.com"
  - CEDAR_TEST_USER1_NAME="Test User 1"
  - CEDAR_TEST_USER2_EMAIL="test2@test.com"
  - CEDAR_TEST_USER2_NAME="Test User 2"
  - CEDAR_EVERYBODY_GROUP_NAME="Everybody"
  - CEDAR_VERSION="1.0.7-SNAPSHOT"
  - CEDAR_VERSION_MODIFIER=""
