# Instructions on setting up Travis CI for the CEDAR Template Editor:
#
# https://github.com/metadatacenter/cedar-conf/wiki/Setting-up-CEDAR-E2E-tests-on-Travis

# Ensure that we are using Ubuntu 14.04, which comes pre-installed with Chrome
sudo: required
dist: trusty

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

# When deployed for testing the Template Editor is effectively a Node application
language: node_js
node_js:
  - '4'

# Do CI only on the develop and master branches
branches:
  only:
    - develop
    - master

# Caching node modules
cache:
  directories:
  - $HOME/node_modules

# Notify the CEDAR core developer mailing list on failures
notifications:
  email:
    recipients:
      - cedar-core-developers@lists.stanford.edu
    on_success: never
    on_failure: always

# Set variables needed by the Template Editor and then start the Xvfb frame buffer
before_install:
  - export CEDAR_HOST=staging.metadatacenter.net
  - export CEDAR_PROFILE=server 
  - export CEDAR_ANALYTICS_KEY=false
  - export CEDAR_SELENIUM_SERVER_JAR=2.53.1-server.jar
  - export CEDAR_CHROME_DRIVER=2.27-x64-chromedriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# Install all dependencies and then install  gulp, protractor, and Selenium
install:
  - npm install
  - npm install -g gulp
  - npm install -g protractor
  - ./node_modules/selenium-standalone/bin/selenium-standalone install

# Run the end-to-end tests
script:
  - gulp e2e

# Variables containing CEDAR test users and passwords
env:
  global:
  - secure: brXMQHBMf0pZ69imCY/kN62AdkOG+B11C1wmNQOoEWNLsjWlxpjgWeBcwwY4pHMuK56bX7wpEbblHhj6WE8qbM3pSrUjjsEAi8x0xly3cVfTrFrxMS6F0ZLjzq9D05OH+lVTrbr+a1SXLWO0GSfWxcGDWY/IR7Mz3cX/jPaKcbI4SSJLon8w1KcNCRYYMK+m9FJS0cmjhkRRVkWdzjXoJdViP0vokqEvAMBMyQLb7AmffGDLlwbXOrPLXpNxELN1ALlgUsi81WhQJ7bENsJDV6LM8QAC6vnbAD8dwPgkAyQRpo1xS6tpXiuEeNeQjuTJ+V5m3IOfdwaEO1cEA56LnzQ+yf4CK0waDIi/iKrjYzkzH9GHOG1vEVHftbG9Z7whyqHq9UZya0yyvKzIK/z9oDOMUljycu3mwxG8uKOFoxfulkecadQNbiTZEXkHqfHv/tdAF+MkX4Jyg3d1h0lxyJ/k2POksLrEIQO140h4s7na8R/iyXFAv2IEuRGoJzAzBsODw4u+q84J3tmlfgVTezf/9fDxes+fK5V9KVcor8FQUigppE/aWAmHfpgzVFf9RsT0OXWh64lA0wVxFX3NrWCJdhU7iFg+Z/lRlLDT33TRCrvOIxkCY1NUYxCIHBEfVtMOr3souEAFdClkr56vtJTDVRhbgvEZNWtQcbB1QOk=
  - secure: NOtz6ntXdoxdMm4dePT6OF2lFWUwnHcIQ8s0JTFhRVulMDWfI5DyNsFPS/zo3Y5LQy1oZBKG5nK1n+m94QiO6dpYSQ2mj6hiMfgIjiuzDHmVlXfNFodKuHVRC9vumlXYnbL5liVWgA3Ja2e5GpaRYBeap5GOz/0rQFgzAK36hDjzj2UCkgnp0aIXExURanp1icyIAWnEJL0/NEaAv/yK/vVYayyaVbOjiiW14u/OBr8ZvJaDLAyfLTRGW1VP93GU9Rn1C7BPQ7J9onFu1K3TvGPnDpynk/7r6/Lbwv06jEy+L5ni9m1dR4xWuQuDXJAR5L3Nf602tbetq2qrhb71UmaZGvl0q1fcCDlGtHsXZud8mTz2sFLWC7tk2OUOJbhaBVRAJo08A/TpojuObCZpunAvlCvAS54TFSEsfeaXevSYK03GZAl/WlQBvgqqtUZCBKy2k5bBfNkv4u9Xd2MaQGXDue0hicrjRVeDqdDwy36J5ewFWQATJ0UatdNoMfGVx7/MEsuPZz2W5SIJR8riCxEeGEbIhYEtLn0ZC3M+OjQSolwBifpIBpemqoekq+onDe37R1ACRM8Cxu/pSqds4CfYbqH4nr1vn2NcDwfBPYsE1K++ykYWpf+rOpMnshqJiENkgZCqAsIcQzRnQY1cwcOHA0rxGjgZHrasvlplbYs=
  - secure: KDg2jcShKt/6vdoTQJIUP3RqBeAYyFclSojP5IgrHOQVZw6De0H1d8TMhoFIV+Ey4BxnQ6cXc8UOqyw+DUgTgwhTjqf3Uw1HuXt7xDH22LF/kIrLa9xPA8/UZWdh+AuD40tR4i8e3ckzeukM09kWMJ4ZREy/ncYSrp9qdTNz99v2brIr2+txHJIUs655VhAX5UFRcr4YmbNNV5vN6akAdbgYW5YXnUBR3x7z9Z8sbChNWMh2rJCituR9deiJNINA6dUnl9h/m+Fy4CuqzeOKTLXheYu6fOsRSfINrrMybx2ly2ZFeGB9srvBue2VpBXhKefKO2/wJtNjqh10ExvpehbD74R2it2xRVRMNpeTDrkrtIvb+Bzch9QUbgdn3HKHlidMScewqJZFw4YY12DFB59Py4QTpWQKhx2gCrGj+g5x9WWnpSwixM+yUTmLkr8h1mW9Q5CQpQR7VlPXx5KbxCXk4xjt3sE6w10SJ7PBxrx8Zii6WUUlK4R3NqCyzXF0e50aEkeRbV0quipPjYlmiDAoKGZk78nPFDl0a9my1iIAv//5A7RUP8xSva+I8yDfGEYA6iymEU3kD+tw0k79WGO0cRdF2oaLlLWF+/jH0EBrhU3eaj1s9EE7/BEffODGwiSnlRIo6Dtu3kHUEbK3LQJlYCFTqlVuEPyQVvfnRBs=
  - secure: upSQEvtBEuKEu8lZlgwfIImNIvnK3I5djNu439Z122smtS9jjmqvUiYbn+nF8og+B5wL+SHcE7lgaPEza7m5seWB6nRjNMKieAP+AoS66h1zOBychVwzgGTyBv7UYwv0WyMmpSflrt8tUf0ohXgaDgkXgS0TzKUlPuYEbjRNemduHN51xCDFUCfa/sd0KV8xgJ2eYOGE0CnDDeG+xQZSUODbWGpKvzUAsH0Yl4F1aXpo7q7aROqmhw28N4Tmk8boWpsmyyK6q8UXpQb0wa147UGbLZ5yE7TqFUt6O66LMIBPIYwRxX5GxTvCpwRR80uTWuzgAZjH1RZuiiQih1+HdlJBzOM/RD0C9z5zkoXo6r0oqcuPaRNzApAlCWjBGliEZ4nNreixOVlzbJ70vPnje18JvprETcw5aPoF3Mnmw3vt6kiCL5sQnQ8R2O8jx6uRL3ZSeIm4U5ixxaF4uCAToMduXNoSFI36ivGAkin9uNm5zh0O+y9SWVwv0HH7goUKknlQxhx7KktDaEy+Fn5s1i+Yo67TYhD1l47I36DlxYtivj9IB4mx4KmHzN23wHQC1AZbB0zUo2qKvKVA4X1aZ+AqNtWQAoqTZVV3Rp5QOTrTNf5gxAvnhyESBpEVf+ZADCAjbmH+3nsgDUEUvtef+FupEQ5baVGMaq/GPFzbIFM=
  - secure: dnsUEpWqOV72vfR0SXsKZflXEqDMUcylQiFkkWiKWP/EFGSCcPdMcURI18bicNUo+1zFlBM0RblH3dGDjYmIjkoL8Q5VJtK0t7OQKrJpTR7KQvEQV17SqwZfKURlNbdFafMfhQJcZN9dX2IErxxpDmTZlJxtSb55vKo3/H9pgcFI20CWwMVWcKR2KeSIbIB0/UG3SCeZZvGG+mQgwUNcdtB8q8bGKfgk0SCDQP2FCXb4ywEWYqfI2fEE/XVTT0RkNcjNs0fMdJ4HAlvrED79Tjyjz5zBDx6JeTUpKEtkpL59KmMn/dAQavWxjgPZ8XF/4FME/kd0RN9Qq92sN5XQSpJUMcQm5YD0IoMWkDxbJkUDgTXe0D+FnZTYPJnri6qhdwPm3VVJCfJ3kQVh2TrUzpGrJeu6XFmCaRd+zku+0qWMPf4a5JU3mDXZRcTnlEo0koLZCnmKOYEEIByVmP8/5Up4zQOPp7ZyCIUW1rksWtZsFEOLRpGM6ixf+pis7/rGl+LHQo+MCGIAnxInyx4MJOORv+XmWp0UmZAjdREZ0tDIHYzd+0SMzP+4tlxkvDNZrBJI9qir7SjwkCDLdGghAXSvhlOLemj6nrqhhP0eO+JWdHNhm9BN6AmY0lBf3o1Ho+xSxHqsrUQoYPkvqAalAL0NrFJsVFfHrlqH8aUMuIE=
  - secure: J2oSyGcrm9CTq+aJ+87JPwPsah5aUlKmQUhhEfn3JZYzoVOIVICTf3a0Fs6CRCBZwsyISA+IwSUMCsno/TIs7VeXx/rhRAr25yZqjv1rpIPEzlhTNfK7H9yDW4lsRqkvLeZVjjnRupySiXLt3Df9WQi0TBp/yCkwCtdgb7UYziUe2VPYVTZezn08GdrYk2TC9fyxDDziXlSWJaEW+dwQH6gj/7vQuFZ5ReGeTGsPUQ/1HlwfpqBveneFnyFkkISIFtKHjGXNatmRx953+WaaJYEOMg4gXga/GeB2bY4e54wz1Qirs3P3vr0mlIDENTopchijOw44ZaPwO2V7CrSWhc2l3y5y6+sQfjCosYAmbSds05O7xjxoTrKkvrb0KfjSXf+H6R2/3erNVfAR4R56FDa1xsSURiGJZ0Zt4sAldxM9CjvTPzsoItfqLnVQCyDqjAR15yFNQQu9JqlvhjXDp6pz7B7DL/RXDIvZtUYI9A5RpYqqpw0C+G59ijD3kYyXcU/VArIJiSE+zUCzJS7xTSHhonLFj1oyFtXAGmkVl0tiIBckvnFAakifejGy4C+/ymisNYAvfj+zSqB7R0m6f9IjOvn9XE6CWk7+QqUSEApcz4IaXjSvanlEzX4kk7fDSVpcbhRGAHbueUWnOWdLHHqw+rA7ScpEKqoyXIfvWR4=
